[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugittive'

[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'tpope/vim-surround'
